python3 ../../../main_pretrain.py \
    --dataset stl10 \
    --backbone resnet18 \
    --data_dir ~/workspace/datasets/ \
    --max_epochs 200 \
    --gpus 0 \
    --accelerator gpu \
    --precision 16 \
    --num_workers 4 \
    --optimizer adam \
    --scheduler warmup_cosine \
    --warmup_epochs 2 \
    --lr 3e-3 \
    --warmup_start_lr 0 \
    --classifier_lr 3e-3 \
    --weight_decay 1e-6 \
    --batch_size 256 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --gaussian_prob 0.0 0.0 \
    --crop_size 96 \
    --num_crops_per_aug 1 1 \
    --min_scale 0.2 \
    --name wmse_res18 \
    --project STL10-200ep \
    --entity kaistaim \
    --wandb \
    --save_checkpoint \
    --method wmse \
    --proj_output_dim 64 \
    --whitening_size 128 \
    --knn_eval \
    --lam 0.1 \
    --tau_decor 0.1 \
    --our_loss False \
