python3 ../../../main_pretrain.py \
    --dataset imagenet100 \
    --backbone resnet18 \
    --data_dir ~/workspace/trung_database/datasets/ \
    --train_dir imagenet-100/train \
    --val_dir imagenet-100/val \
    --max_epochs 200 \
    --gpus 4,5,6,7 \
    --accelerator gpu \
    --strategy ddp \
    --precision 16 \
    --optimizer sgd \
    --scheduler warmup_cosine \
    --lr 0.3 \
    --classifier_lr 0.1 \
    --weight_decay 1e-4 \
    --batch_size 256 \
    --num_workers 4 \
    --brightness 0.4 0.0 \
    --contrast 0.4 0.0 \
    --saturation 0.4 0.0 \
    --hue 0.1 0.0 \
    --gaussian_prob 0.5 0.0 \
    --solarization_prob 0.0 0.0 \
    --num_crops_per_aug 1 1 \
    --name ressl_res18 \
    --project Imagenet100-200ep \
    --entity kaistaim \
    --wandb \
    --save_checkpoint \
    --method ressl \
    --proj_output_dim 256 \
    --proj_hidden_dim 4096 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 1.0 \
    --momentum_classifier \
    --temperature_q 0.1 \
    --temperature_k 0.04
    --knn_eval \
    --lam 0.1 \
    --tau_decor 0.1 \
    --our_loss False \
